import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import path from 'node:path';
export async function browserFlow({groupId}){
 const browser=await chromium.launch({...(process.env.E2E_CHROME?{executablePath:process.env.E2E_CHROME}:{}),headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});
 const teacher=await browser.newPage({viewport:{width:1440,height:1100}}),errors=[];teacher.on('pageerror',e=>errors.push(e.message));
 async function login(page,email){await page.goto('http://localhost:3000/login');await page.locator('input[name="email"]').fill(email);await page.locator('input[name="password"]').fill('testPassword1');await page.locator('button[type="submit"]').click();await page.waitForURL(/dashboard/);}
 try{
  await login(teacher,'teacher@e2e.test');console.log('E2E teacher login');
  await teacher.goto('http://localhost:3000/worksheets/upload');await teacher.locator('input[type="file"]').setInputFiles(new URL('../fixtures/worksheet.pdf',import.meta.url).pathname);await teacher.getByPlaceholder('Título del worksheet').fill('Browser interactive worksheet');
  const upload=teacher.waitForResponse(r=>r.url().endsWith('/api/worksheets/upload')&&r.request().method()==='POST');await teacher.getByRole('button',{name:/Guardar|Save/i}).first().click();const uploaded=await (await upload).json();const id=uploaded.data.worksheet.id;await teacher.waitForURL(/dashboard\/teacher/);console.log('E2E PDF upload');
  await teacher.goto(`http://localhost:3000/worksheets/${id}`);await teacher.getByRole('link',{name:'Make Interactive',exact:true}).click();await teacher.getByTestId('pdf-page').locator('canvas').waitFor();await teacher.getByText('Loading PDF page…').waitFor({state:'hidden'});console.log('E2E PDF renders in editor');
  async function draw(tool,x,y,w,h){await teacher.getByRole('button',{name:`+ ${tool}`,exact:true}).click();const box=await teacher.getByTestId('pdf-page').boundingBox();const x1=box.x+box.width*x,y1=box.y+box.height*y;await teacher.mouse.move(x1,y1);await teacher.mouse.down();await teacher.mouse.move(x1+box.width*w,y1+box.height*h,{steps:10});await teacher.mouse.up();}
  await draw('Text Answer',.15,.12,.35,.07);await teacher.getByLabel('Field label',{exact:true}).fill('Verb answer');await teacher.getByLabel('Accepted answers (one per line)',{exact:true}).fill('am');await teacher.getByLabel('Points',{exact:true}).fill('2');
  await draw('Teacher Review',.15,.32,.6,.12);await teacher.getByLabel('Field label',{exact:true}).fill('Explain answer');await teacher.getByLabel('Points',{exact:true}).fill('3');await teacher.getByLabel('Model answer (teacher only)',{exact:true}).fill('A clear explanation');await teacher.getByLabel('Student feedback',{exact:true}).selectOption('full');
  await teacher.getByRole('button',{name:'Save interactive worksheet',exact:true}).click();await teacher.getByRole('status').filter({hasText:'Interactive fields saved'}).waitFor();
  await teacher.getByRole('button',{name:'Next',exact:true}).click();await teacher.getByText('Page 2 / 2',{exact:true}).waitFor();await teacher.getByRole('button',{name:'Previous',exact:true}).click();
  await teacher.screenshot({path:new URL('./results/editor-desktop.png',import.meta.url).pathname,fullPage:true});
  await teacher.goto(`http://localhost:3000/worksheets/${id}`);await teacher.getByRole('button',{name:'Publish',exact:true}).click();await teacher.getByRole('button',{name:'Unpublish',exact:true}).waitFor();
  await teacher.goto(`http://localhost:3000/groups/${groupId}`);await teacher.getByRole('button',{name:'Assign Worksheet',exact:true}).click();await teacher.getByText('Browser interactive worksheet',{exact:true}).last().click();const assign=teacher.waitForResponse(r=>r.url().includes('/assignments')&&r.request().method()==='POST');await teacher.getByRole('button',{name:/Assign Worksheet|Assign to Group/i}).last().click();assert.ok([200,201].includes((await assign).status()));console.log('E2E save publish assign');
  const student=await browser.newPage({viewport:{width:390,height:844}});student.on('pageerror',e=>errors.push(e.message));await login(student,'student@e2e.test');await student.getByRole('link',{name:/worksheet: Browser interactive worksheet/}).click();await student.getByRole('button',{name:'Start / resume activity',exact:true}).click();await student.getByLabel('Verb answer',{exact:true}).fill('am');await student.getByLabel('Explain answer',{exact:true}).fill('Because I is followed by am.');await student.getByRole('button',{name:'Save answers',exact:true}).click();await student.getByRole('status').filter({hasText:'Answers saved'}).waitFor();
  await student.reload();await student.getByRole('button',{name:'Start / resume activity',exact:true}).click();assert.equal(await student.getByLabel('Verb answer',{exact:true}).inputValue(),'am');await student.screenshot({path:new URL('./results/student-mobile.png',import.meta.url).pathname,fullPage:true});
  await student.getByRole('button',{name:'Submit worksheet',exact:true}).click();await student.getByRole('status').filter({hasText:'Submission received'}).waitFor();console.log('E2E mobile answers saved resumed submitted');
  await teacher.goto(`http://localhost:3000/worksheets/${id}/review`);await teacher.getByRole('button').filter({hasText:'Student Test'}).click();const articles=teacher.locator('article');await articles.filter({hasText:'Explain answer'}).getByLabel('Points awarded').fill('3');await articles.filter({hasText:'Explain answer'}).getByLabel('Teacher comment').fill('Well explained');await teacher.getByRole('button',{name:'Save Review',exact:true}).click();await teacher.getByRole('status').waitFor();
  await student.getByRole('button',{name:'Refresh results',exact:true}).click();await student.getByText(/^5(?:\.00)? \/ 5 · 100%$/).first().waitFor();console.log('E2E teacher review recalculates student result');
  await teacher.goto('http://localhost:3000/dashboard/teacher');await teacher.getByRole('button',{name:'Analytics',exact:true}).click();await teacher.getByText('Learning Analytics',{exact:true}).waitFor();await teacher.getByText('100%',{exact:true}).first().waitFor();await teacher.getByRole('button',{name:'Most difficult questions',exact:true}).click();await teacher.getByText('Verb answer',{exact:true}).waitFor();await teacher.screenshot({path:new URL('./results/analytics-desktop.png',import.meta.url).pathname,fullPage:true});console.log('E2E analytics final score and question results');
  assert.deepEqual(errors,[]);console.log('E2E PASS: full browser flow, desktop + mobile, no uncaught React errors');
 }catch(e){await teacher.screenshot({path:new URL('./results/e2e-failure.png',import.meta.url).pathname,fullPage:true});throw e;}finally{await browser.close();}
}
